# Example deployment with security issues for testing

apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insecure-app
  template:
    metadata:
      labels:
        app: insecure-app
    spec:
      containers:
      - name: web
        image: nginx:latest  # NIST-4.1.1: Using latest tag
        ports:
        - containerPort: 80
        securityContext:
          privileged: true  # CIS-5.1.2: Privileged container
          allowPrivilegeEscalation: true  # CIS-5.1.3: Allows privilege escalation
          runAsUser: 0  # NIST-4.2.1: Running as root
          readOnlyRootFilesystem: false  # NIST-4.2.1: Writable root filesystem
        env:
        - name: DATABASE_PASSWORD
          value: "supersecret123"  # NIST-4.5.1: Secret in environment variable
        # Missing resource limits - NIST-4.4.1
        # No seccomp profile - CIS-5.1.8
        # No AppArmor profile - CIS-5.1.9
      hostNetwork: true  # CIS-5.1.5: Using host network
      hostPID: true      # CIS-5.1.6: Using host PID
      hostIPC: true      # CIS-5.1.7: Using host IPC
      automountServiceAccountToken: true  # CIS-5.1.10: Auto-mounting service account token